---


#- { name: '/etc/hdp/nox-hdp2', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/hadoop', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/hbase', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/zookeeper', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/pig', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/hive', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/oozie', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/oozie-server', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/hcatalog', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#
- name: "** nox ** create directory for hdp hadoop config on slavenodes"
  action: file path={{ item.name }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  with_items:
    - { name: '/etc/hdp', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/hadoop', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/hbase', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/zookeeper', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/pig', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/hive', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/oozie', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/oozie-server', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_dn }}/hcatalog', owner: 'hadoop', group: 'hadoop', mode: '0755' }
  when: "'slavenodes' in group_names"
  tags: get-hadoop2-config


#- { name: '/ebay/hdp/nox-hdp2', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/hadoop', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/hbase', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/zookeeper', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/pig', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/hive', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/oozie', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/oozie-server', owner: 'hadoop', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/hcatalog', owner: 'hadoop', group: 'hadoop', mode: '0755' }
- name: "** nox ** create directory for hdp hadoop config on masternodes"
  action: file path={{ item.name }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
  with_items:
    - { name: '/etc/hdp', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '/ebay/hdp', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/hadoop', owner: 'root', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/hbase', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/zookeeper', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/pig', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/hive', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/oozie', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/oozie-server', owner: 'hadoop', group: 'hadoop', mode: '0755' }
    - { name: '{{ hdp2_conf_dir_en }}/hcatalog', owner: 'hadoop', group: 'hadoop', mode: '0755' }
  when: "'masternodes' in group_names"
  tags: get-hadoop2-config

- name: "** nox ** create link for hdp hadoop config directory on masternodes"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/ebay/hdp/nox', dest: '/etc/hdp/nox', owner: 'root', group: 'hadoop' }
  when: "'masternodes' in group_names"
  tags: get-hadoop2-config


- name: "** nox ** ensure hadoop log directories are present on slavenodes"
  action: file path={{ item.name }} owner=hadoop group=hadoop mode={{ item.mode }} state=directory
  with_items:
    - { name: '/var/log/hadoop', mode: '0755' }
    - { name: '/var/log/hadoop/hadoop', mode: '0755' }
    - { name: '/var/log/hadoop/hbase', mode: '0755' }
    - { name: '/var/log/hadoop/zookeeper', mode: '0755' }
    - { name: '/var/log/hadoop/hive', mode: '0775' }
    - { name: '/var/log/hadoop/pig', mode: '0775' }
    - { name: '/var/log/hadoop/oozie-server', mode: '0775' }
    - { name: '/var/log/hadoop/oozie', mode: '0775' }
    - { name: '/var/log/hadoop/hcatalog', mode: '0775' }
  when: "'slavenodes' in group_names"
  tags: 
    - hadoop-logs
    - get-hadoop2-config

- name: "** nox ** ensure hadoop log directories are present on masternodes"
  action: file path={{ item.name }} owner=hadoop group=hadoop mode={{ item.mode }} state=directory
  with_items:
    - { name: '/hadoop/logs', mode: '0755' }
    - { name: '/hadoop/logs/hadoop', mode: '0755' }
    - { name: '/hadoop/logs/hbase', mode: '0755' }
    - { name: '/hadoop/logs/zookeeper', mode: '0755' }
    - { name: '/hadoop/logs/hive', mode: '0775' }
    - { name: '/hadoop/logs/pig', mode: '0775' }
    - { name: '/hadoop/logs/oozie-server', mode: '0775' }
    - { name: '/hadoop/logs/oozie', mode: '0775' }
    - { name: '/hadoop/logs/hcatalog', mode: '0775' }
  when: "'masternodes' in group_names"
  tags: 
    - hadoop-logs
    - get-hadoop2-config

####
####

- name: "** nox ** install hadoop2 config on masternodes"
  action: synchronize src=/var/lib/ansible/hadoop-ansible/playbooks/files/hdp2/nox/{{ item.src }} dest={{ hdp2_conf_dir_en }}/{{ item.dest }}
  with_items:
    - { src: 'zookeeper/conf/', dest: 'zookeeper/conf/' }
    - { src: 'hadoop/conf/', dest: 'hadoop/conf/' }
    - { src: 'hbase/conf/', dest: 'hbase/conf/' }
    - { src: 'hive/conf/', dest: 'hive/conf/' }
    - { src: 'pig/conf/', dest: 'pig/conf/' }
    - { src: 'oozie/conf/', dest: 'oozie/conf/' }
    - { src: 'oozie-server/conf/', dest: 'oozie-server/conf/' }
    - { src: 'hcatalog/conf/', dest: 'hcatalog/conf/' }
  when: "'masternodes' in group_names"
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs


- name: "** nox ** install hadoop2 config on slavenodes"
  action: synchronize src=/var/lib/ansible/hadoop-ansible/playbooks/files/hdp2/nox/{{ item.src }} dest={{ hdp2_conf_dir_dn }}/{{ item.dest }}
  with_items:
    - { src: 'zookeeper/conf/', dest: 'zookeeper/conf/' }
    - { src: 'hadoop/conf/', dest: 'hadoop/conf/' }
    - { src: 'hbase/conf/', dest: 'hbase/conf/' }
    - { src: 'hive/conf/', dest: 'hive/conf/' }
    - { src: 'pig/conf/', dest: 'pig/conf/' }
    - { src: 'oozie/conf/', dest: 'oozie/conf/' }
    - { src: 'oozie-server/conf/', dest: 'oozie-server/conf/' }
    - { src: 'hcatalog/conf/', dest: 'hcatalog/conf/' }
  when: "'slavenodes' in group_names"
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs


- name: "** nox ** chown hadoop config on masternodes"
  action: command chown -R hadoop:hadoop {{ hdp2_conf_dir_en }}
  when: "'masternodes' in group_names"
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs

- name: "** nox ** chown hadoop config on slavenodes"
  action: command chown -R hadoop:hadoop {{ hdp2_conf_dir_dn }}
  when: "'slavenodes' in group_names"
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs



#- { name: '/etc/hdp/nox-hdp2', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/hadoop', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/etc/hdp/nox-hdp2/hadoop/conf', owner: 'root', group: 'hadoop', mode: '0755' }
#
- name: "** nox ** set root ownership to hadoop config dirs and files on slavenodes"
  action: file path={{ item.name }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state={{ item.state }}
  with_items:
    - { name: '{{ hdp2_conf_dir_dn }}', owner: 'root', group: 'hadoop', mode: '0755', state: 'directory' }
    - { name: '{{ hdp2_conf_dir_dn }}/hadoop', owner: 'root', group: 'hadoop', mode: '0755', state: 'directory' }
    - { name: '{{ hdp2_conf_dir_dn }}/hadoop/conf', owner: 'root', group: 'hadoop', mode: '0755', state: 'directory' }
    - { name: '{{ hdp2_conf_dir_dn }}/hadoop/conf/container-executor.cfg', owner: 'root', group: 'hadoop', mode: '0400', state: 'file' }
  when: "'slavenodes' in group_names"
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs


#- { name: '/ebay/hdp/nox-hdp2', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/hadoop', owner: 'root', group: 'hadoop', mode: '0755' }
#- { name: '/ebay/hdp/nox-hdp2/hadoop/conf', owner: 'root', group: 'hadoop', mode: '0755' }
#
- name: "** nox ** set root ownership to hadoop config dirs and files on masternodes"
  action: file path={{ item.name }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state={{ item.state }}
  with_items:
    - { name: '{{ hdp2_conf_dir_en }}', owner: 'root', group: 'hadoop', mode: '0755', state: 'directory' }
    - { name: '{{ hdp2_conf_dir_en }}/hadoop', owner: 'root', group: 'hadoop', mode: '0755', state: 'directory' }
    - { name: '{{ hdp2_conf_dir_en }}/hadoop/conf', owner: 'root', group: 'hadoop', mode: '0755', state: 'directory'  }
    - { name: '{{ hdp2_conf_dir_en }}/hadoop/conf/container-executor.cfg', owner: 'root', group: 'hadoop', mode: '0400', state: 'file' }
  when: "'masternodes' in group_names"
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs

- name: "** nox ** deploy pingfederate-agent-config.txt file" 
  action: copy src={{ item }} dest=/etc/hadoop/pingfederate-agent-config.txt owner=hadoop group=hadoop mode=0644
  with_items:
    - /var/lib/ansible/hadoop-ansible/playbooks/files/hdp2/nox/hadoop/conf/pingfederate-agent-config.txt
  tags: 
    - get-hadoop2-config
    - deploy-hdp2-configs

# daemontools configs
- name: "** nox ** copy file HADOOP_SECURE_DN_USER"
  action: copy src={{ item }} dest=/service/datanode/env/HADOOP_SECURE_DN_USER owner=root group=root mode=0644
  with_items:
    - /var/lib/ansible/hadoop-ansible/playbooks/files/HADOOP_SECURE_DN_USER
  when: "'slavenodes' in group_names"
  tags: get-hadoop2-config

- name: "** nox ** copy file historyserver daemontools run script"
  action: copy src={{ item }} dest=/service/historyserver/run owner=root group=root mode=0755
  with_items:
    - /var/lib/ansible/hadoop-ansible/playbooks/files/historyserver.dt.run.HDP2
  when: "'historyserver' in group_names"
  tags: get-hadoop2-config
