---

- name: "** nox ** copy ebay-hdp-hadoop2 repo file"
  action: copy src={{ item }} dest=/etc/yum.repos.d/ebay-hdp-hadoop2-x86_64.repo owner=root group=root mode=0644
  with_items:
    - /var/lib/ansible/hadoop-ansible/playbooks/files/ebay-hdp-hadoop2-x86_64.repo
  tags: install-ebay-hdp2-hadoop

- name: "** nox ** yum clean all on repo"
  action: command yum clean all
  tags: install-ebay-hdp2-hadoop

- name: "** nox ** check if old hdp2 installation is present"
  action: stat path={{ item }}
  with_items:
    - /apache/hive-0.12.0.2.0.6.0-76
    - /apache/zookeeper-3.4.5.2.0.6.0-76
    - /apache/oozie-4.0.0.2.0.6.0-76
    - /apache/pig-0.12.0.2.0.6.0-76
    - /apache/hbase-0.96.0.2.0.6.0-76-hadoop2
    - /apache/hadoop-2.2.0.2.0.6.0-76
  register: oldinstalldir
  tags: install-ebay-hdp2-hadoop

- name: "** nox ** backup old hdp2 installation"
  action: command mv {{ item.item }} {{ item.item }}.BAK
  with_items: oldinstalldir.results
  when: item.stat.isdir is defined and item.stat.isdir == true
  tags: install-ebay-hdp2-hadoop

# hive
##- name: "** nox ** hive check if old hdp2 installation present"
##  action: stat path=/apache/hive-0.12.0.2.0.6.0-76
##  register: hivedir
##  tags: install-ebay-hdp2-hadoop
##  
##- name: "** nox ** hive backup old hdp2 installation" 
##  action: command mv /apache/hive-0.12.0.2.0.6.0-76 /apache/hive-0.12.0.2.0.6.0-76.BAK
##  when: hivedir.stat.isdir is defined and hivedir.stat.isdir == true
##
# zookeeper
##- name: "** nox ** zookeeper check if old hdp2 installation present"
##  action: stat path=/apache/zookeeper-3.4.5.2.0.6.0-76
##  register: zoodir
##  tags: install-ebay-hdp2-hadoop
##
##- name: "** nox ** zookeeper backup old hdp2 installation"
##  action: command mv /apache/zookeeper-3.4.5.2.0.6.0-76 /apache/zookeeper-3.4.5.2.0.6.0-76.BAK
##  when: zoodir.stat.isdir is defined and zoodir.stat.isdir == true
##
# oozie
##- name: "** nox ** oozie check if old hdp2 installation present"
##  action: stat path=/apache/oozie-4.0.0.2.0.6.0-76
##  register: ooziedir
##  tags: install-ebay-hdp2-hadoop
##
##- name: "** nox ** oozie backup old hdp2 installation"
##  action: command mv /apache/oozie-4.0.0.2.0.6.0-76 /apache/oozie-4.0.0.2.0.6.0-76.BAK
##  when: ooziedir.stat.isdir is defined and ooziedir.stat.isdir == true
##
# pig
##- name: "** nox ** pig check if old hdp2 installation present"
##  action: stat path=/apache/pig-0.12.0.2.0.6.0-76
##  register: pigdir
##  tags: install-ebay-hdp2-hadoop
##
##- name: "** nox ** pig backup old hdp2 installation"
##  action: command mv /apache/pig-0.12.0.2.0.6.0-76 /apache/pig-0.12.0.2.0.6.0-76.BAK
##  when: pigdir.stat.isdir is defined and pigdir.stat.isdir == true
##
# hbase
##- name: "** nox ** hbase check if old hdp2 installation present"
##  action: stat path=/apache/hbase-0.96.0.2.0.6.0-76-hadoop2
##  register: hbasedir
##  tags: install-ebay-hdp2-hadoop
##
##- name: "** nox ** hbase backup old hdp2 installation"
##  action: command mv /apache/hbase-0.96.0.2.0.6.0-76-hadoop2 /apache/hbase-0.96.0.2.0.6.0-76-hadoop2.BAK
##  when: hbasedir.stat.isdir is defined and hbasedir.stat.isdir == true
##  tags: install-ebay-hdp2-hadoop
##
##
# hadoop
##- name: "** nox ** hadoop check if old hdp2 installation present"
##  action: stat path=/apache/hadoop-2.2.0.2.0.6.0-76
##  register: hadoopdir
##  tags: install-ebay-hdp2-hadoop
##
##- name: "** nox ** hadoop backup old hdp2 installation"
##  action: command mv /apache/hadoop-2.2.0.2.0.6.0-76 /apache/hadoop-2.2.0.2.0.6.0-76.BAK
##  when: hadoopdir.stat.isdir is defined and hadoopdir.stat.isdir == true
##  tags: install-ebay-hdp2-hadoop
##


- name: "** nox ** remove old hdp2 hit-apache-hadoop pkgs"
  action: yum name={{ item }} state=removed
  with_items:
    - hit-apache-hadoop-hadoop-2.2.0.2.0.6.0
    - hit-apache-hadoop-hbase-0.96.0.2.0.6.0
    - hit-apache-hadoop-oozie-4.0.0.2.0.6.0
    - hit-apache-hadoop-hive-0.12.0.2.0.6.0
    - hit-apache-hadoop-pig-0.12.0.2.0.6.0
    - hit-apache-hadoop-zookeeper-3.4.5.2.0.6.0
  tags: install-ebay-hdp2-hadoop


#- ebay-hdp-lw-hive-0.12.0.2.0.6.0-38
#- ebay-hdp-lw-oozie-4.0.0.2.0.6.0-38
#- ebay-hdp-lw-hbase-0.96.0.2.0.6.0-38
#- ebay-hdp-lw-hadoop-2.2.0.2.0.6.0-38
#- ebay-hdp-lw-zookeeper-3.4.5.2.0.6.0-38
#- ebay-hdp-lw-pig-0.12.0.2.0.6.0-38
#- ebay-hdp-lw-hcatalog-0.12.0.2.0.6.0-38
#- bigtop-jsvc-1.0.10
#
# install ebay-hdp2-lzo-native-1.0-1 lzo libraries after enabling HDP2 build 
- name: "** nox ** install ebay-hdp-lw-hadoop pkgs"
  action: yum disablerepo=hit-hadoop-x86_64 enablerepo=ebay-hdp-hadoop2-x86_64 pkg={{ item }} state=installed
  with_items:
    - '{{ hdp2_rpm_hive }}'
    - '{{ hdp2_rpm_oozie }}'
    - '{{ hdp2_rpm_hbase }}'
    - '{{ hdp2_rpm_hadoop }}'
    - '{{ hdp2_rpm_zookeeper }}'
    - '{{ hdp2_rpm_pig }}'
    - '{{ hdp2_rpm_hcatalog }}'
    - '{{ hdp2_rpm_jsvc }}'
  tags: install-ebay-hdp2-hadoop

#- { src: 'hadoop-ebay.jar', dest: '/apache/hadoop-2.2.0.2.0.6.0-38/share/hadoop/common/lib/hadoop-ebay.jar' }
#- { src: 'opentoken-adapter-2.4.jar', dest: '/apache/hadoop-2.2.0.2.0.6.0-38/share/hadoop/common/lib/opentoken-adapter-2.4.jar' }
#- { src: 'opentoken-agent-2.4.jar', dest: '/apache/hadoop-2.2.0.2.0.6.0-38/share/hadoop/common/lib/opentoken-agent-2.4.jar' }
# get_url hadoop jars
- name: "** nox ** deploy hdmi hdp hadoop jars"
  action: get_url url=http://installsvc.vip.phx.ebay.com/packages/hs/hdp2-lw/jars/{{ item.src }} dest={{ item.dest }} owner=hadoop group=hadoop mode=0644
  with_items:
    - { src: 'hadoop-ebay.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/hadoop-ebay.jar' }
    - { src: 'opentoken-adapter-2.4.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/opentoken-adapter-2.4.jar' }
    - { src: 'opentoken-agent-2.4.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/opentoken-agent-2.4.jar' }
  tags: install-ebay-hdp2-hadoop


#- hive-0.12.0.2.0.6.0-38
#- oozie-4.0.0.2.0.6.0-38
#- hbase-0.96.0.2.0.6.0-38-hadoop2
#- zookeeper-3.4.5.2.0.6.0-38
#- pig-0.12.0.2.0.6.0-38
#- hcatalog-0.12.0.2.0.6.0-38
#- hadoop-2.2.0.2.0.6.0-38
#
# 
# ebay-hdp-lw-hadoop build-61 RPM will install with owner:group set to user 'hadoop'
#- name: "** nox ** chown hdp2 installation, except hadoop dir"
#  action: command chown -R hadoop:hadoop /apache/{{ item }}
#  with_items: 
#    - '{{ hdp2_hive }}'
#    - '{{ hdp2_ooziesrv }}'
#    - '{{ hdp2_hbase }}'
#    - '{{ hdp2_zookeeper }}'
#    - '{{ hdp2_pig }}'
#    - '{{ hdp2_hcatalog }}'
#    - '{{ hdp2_hadoop }}'
#  tags: install-ebay-hdp2-hadoop


#    - /apache/hadoop-2.2.0.2.0.6.0-38
#    - /apache/hadoop-2.2.0.2.0.6.0-38/etc
#    - /apache/hadoop-2.2.0.2.0.6.0-38/etc/hadoop
- name: "** nox ** stat hdp2 install directories"
  action: stat path={{ item }}
  with_items:
    - /apache
    - '/apache/{{ hdp2_hadoop }}'
    - '/apache/{{ hdp2_hadoop }}/etc'
    - '/apache/{{ hdp2_hadoop }}/etc/hadoop'
  register: hdp2installdirs
  tags: install-ebay-hdp2-hadoop

- name: "** nox ** chown hdp2 hadoop dir"
  action: file path={{ item.item }} owner=root group=hadoop mode=0755
  with_items: hdp2installdirs.results
  when: item.stat.isdir is defined and item.stat.isdir == true
  tags: install-ebay-hdp2-hadoop


##- name: "** nox ** chown hdp2 hadoop dir"
##  action: file path={{ item.src }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
##  with_items: 
##    - { src: '/apache', owner: 'root', group: 'hadoop', mode: '755' }
##    - { src: '/apache/hadoop-2.2.0.2.0.6.0-38', owner: 'root', group: 'hadoop', mode: '755' }
##    - { src: '/apache/hadoop-2.2.0.2.0.6.0-38/etc', owner: 'root', group: 'hadoop', mode: '755' }
##    - { src: '/apache/hadoop-2.2.0.2.0.6.0-38/etc/hadoop', owner: 'root', group: 'hadoop', mode: '775' }
##  tags: install-ebay-hdp2-hadoop

##- name: "** nox ** rename new hdp2 conf dir if present"
##  action: shell mv /apache/hadoop/etc/{{ item.item }} /apache/hadoop/etc/{{ item.item }}.BAK.$(date +%Y-%m-%d.%H%M%S)
##  with_items: hdp2confdir.results
##  when: item.stat.isdir is defined and item.stat.isdir == true
##  tags: install-ebay-hdp2-hadoop



