---

- name: "** nox ** touch /var/lib/service/puppet/down"
  action: command touch /var/lib/service/puppet/down
  tags: disable-puppet

- name: "** nox ** shutdown puppet"
  action: command svc -d /service/puppet
  tags: disable-puppet

- name: "** nox ** remove /service/puppet link"
  action: file path=/service/puppet state=absent
  tags: disable-puppet

- name: "** nox ** set /var/lib/service/puppet/run mode to 0"
  action: file path=/var/lib/service/puppet/run mode=0000
  tags: disable-puppet
