---

# hit-hadoop1-x86_64.repo
- name: "** nox ** copy hadoop1 repo file"
  action: copy src={{ item }} dest=/etc/yum.repos.d/hit-hadoop1-x86_64.repo owner=root group=root mode=0644
  with_items:
    - /var/lib/ansible/hadoop-ansible/playbooks/files/hit-hadoop1-x86_64.repo
  tags: install-hit-apache-hadoop

- name: "** nox ** yum clean all on repo"
  action: command yum clean all
  tags: install-hit-apache-hadoop

##- name: "** nox ** check if old hdp2 installation present"
##  action: stat=/apache/{{ item }}
##  with_items:
##    - hive-0.12.0.2.0.6.0-76
##    - zookeeper-3.4.5.2.0.6.0-76
##    - oozie-4.0.0.2.0.6.0-76
##    - pig-0.12.0.2.0.6.0-76
##    - hbase-0.96.0.2.0.6.0-76-hadoop2
##    - hadoop-2.2.0.2.0.6.0-76
##  register: oldinstalldir
##  tags: install-hit-apache-hadoop

# hive
- name: "** nox ** hive check if old hdp2 installation present"
  action: stat path=/apache/hive-0.12.0.2.0.6.0-76
  register: hivedir
  tags: install-hit-apache-hadoop
  
- name: "** nox ** hive backup old hdp2 installation" 
  action: shell mv /apache/hive-0.12.0.2.0.6.0-76 /apache/hive-0.12.0.2.0.6.0-76.BAK.$(date +%F.%T).2250
  when: hivedir.stat.isdir is defined and hivedir.stat.isdir == true

# zookeeper
- name: "** nox ** zookeeper check if old hdp2 installation present"
  action: stat path=/apache/zookeeper-3.4.5.2.0.6.0-76
  register: zoodir
  tags: install-hit-apache-hadoop

- name: "** nox ** zookeeper backup old hdp2 installation"
  action: shell mv /apache/zookeeper-3.4.5.2.0.6.0-76 /apache/zookeeper-3.4.5.2.0.6.0-76.BAK.$(date +%F.%T).2250
  when: zoodir.stat.isdir is defined and zoodir.stat.isdir == true

# oozie
- name: "** nox ** oozie check if old hdp2 installation present"
  action: stat path=/apache/oozie-4.0.0.2.0.6.0-76
  register: ooziedir
  tags: install-hit-apache-hadoop

- name: "** nox ** oozie backup old hdp2 installation"
  action: shell mv /apache/oozie-4.0.0.2.0.6.0-76 /apache/oozie-4.0.0.2.0.6.0-76.BAK.$(date +%F.%T).2250
  when: ooziedir.stat.isdir is defined and ooziedir.stat.isdir == true

# pig
- name: "** nox ** pig check if old hdp2 installation present"
  action: stat path=/apache/pig-0.12.0.2.0.6.0-76
  register: pigdir
  tags: install-hit-apache-hadoop

- name: "** nox ** pig backup old hdp2 installation"
  action: shell mv /apache/pig-0.12.0.2.0.6.0-76 /apache/pig-0.12.0.2.0.6.0-76.BAK.$(date +%F.%T).2250
  when: pigdir.stat.isdir is defined and pigdir.stat.isdir == true

# hbase
- name: "** nox ** hbase check if old hdp2 installation present"
  action: stat path=/apache/hbase-0.96.0.2.0.6.0-76-hadoop2
  register: hbasedir
  tags: install-hit-apache-hadoop

- name: "** nox ** hbase backup old hdp2 installation"
  action: shell mv /apache/hbase-0.96.0.2.0.6.0-76-hadoop2 /apache/hbase-0.96.0.2.0.6.0-76-hadoop2.BAK.$(date +%F.%T).2250
  when: hbasedir.stat.isdir is defined and hbasedir.stat.isdir == true


# hadoop
- name: "** nox ** hadoop check if old hdp2 installation present"
  action: stat path=/apache/hadoop-2.2.0.2.0.6.0-76
  register: hadoopdir
  tags: install-hit-apache-hadoop

- name: "** nox ** hadoop backup old hdp2 installation"
  action: shell mv /apache/hadoop-2.2.0.2.0.6.0-76 /apache/hadoop-2.2.0.2.0.6.0-76.BAK.$(date +%F.%T).2250
  when: hadoopdir.stat.isdir is defined and hadoopdir.stat.isdir == true



- name: "** nox ** remove old hdp2 hit-apache-hadoop pkgs"
  action: yum name={{ item }} state=removed
  with_items:
    - hit-apache-hadoop-hadoop-2.2.0.2.0.6.0
    - hit-apache-hadoop-hbase-0.96.0.2.0.6.0
    - hit-apache-hadoop-oozie-4.0.0.2.0.6.0
    - hit-apache-hadoop-hive-0.12.0.2.0.6.0
    - hit-apache-hadoop-pig-0.12.0.2.0.6.0
    - hit-apache-hadoop-zookeeper-3.4.5.2.0.6.0
  tags: install-hit-apache-hadoop

- name: "** nox ** unlink any hadoop related links from previous installation"
  action: file path={{ item }} state=absent
  with_items:
    - /apache/hbase
    - /apache/hive
    - /apache/zookeeper
    - /apache/oozie-server
    - /apache/oozie
    - /apache/pig
    - /apache/hadoop
    - /apache/hcatalog
  tags: install-hit-apache-hadoop


#- hit-apache-hadoop-hive-0.0.1
#- hit-apache-hadoop-oozie-0.0.1
#- hit-apache-hadoop-hbase-0.0.1
#- hit-apache-hadoop-hadoop-0.0.1
#- hit-apache-hadoop-zookeeper-0.0.1
#- hit-apache-hadoop-pig-0.0.1
#- hit-apache-hadoop-hcatalog-0.0.1
- name: "** nox ** install hit-apache-hadoop pkgs"
  action: yum disablerepo=hit-hadoop-x86_64 enablerepo=hit-hadoop1-x86_64 pkg={{ item }} state=installed
  with_items:
    - '{{ hdp1_rpm_hive }}'
    - '{{ hdp1_rpm_oozie }}'
    - '{{ hdp1_rpm_hbase }}'
    - '{{ hdp1_rpm_hadoop }}'
    - '{{ hdp1_rpm_zookeeper }}'
    - '{{ hdp1_rpm_pig }}'
    - '{{ hdp1_rpm_hcatalog }}'
  tags: install-hit-apache-hadoop

#- { src: '/apache/hbase-0.94.6.101-security', dest: '/apache/hbase', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/hive-0.11.0.1.3.0.0-107', dest: '/apache/hive', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/hcatalog-0.11.0.1.3.0.0-107', dest: '/apache/hcatalog', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/zookeeper-3.4.5.1.3.0.0-107', dest: '/apache/zookeeper', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/oozie-3.1.3.15-1', dest: '/apache/oozie-server', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/oozie-3.1.3.15-1/oozie-client-3.1.3.15', dest: '/apache/oozie', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/pig-0.11.1.1.3.0.0-107', dest: '/apache/pig', owner: 'hadoop', group: 'hadoop' }
#- { src: '/apache/hadoop-1.2.0.101', dest: '/apache/hadoop', owner: 'hadoop', group: 'hadoop' }
- name: "** nox ** create links for hadoop sfw directories"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link
  with_items:
    - { src: '/apache/{{ hdp1_hbase }}', dest: '/apache/hbase', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_hive }}', dest: '/apache/hive', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_hcatalog }}', dest: '/apache/hcatalog', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_zookeeper }}', dest: '/apache/zookeeper', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_ooziesrv }}', dest: '/apache/oozie-server', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_oozie }}', dest: '/apache/oozie', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_pig }}', dest: '/apache/pig', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_hadoop }}', dest: '/apache/hadoop', owner: 'hadoop', group: 'hadoop' }
  tags: install-hit-apache-hadoop

- name: "** nox ** ensure additional apache hadoop directories are present"
  action: file path={{ item }} owner=hadoop group=hadoop mode=0755 state=directory
  with_items:
    - /apache
    - /apache/lib
    - /apache/hadoop/lib
    - /apache/hadoop/pids
  tags: install-hit-apache-hadoop

# install libsnappy softlink
- name: "** nox ** create link for libsnappy"
  action: file src={{ item.src }} dest={{ item.dest }} owner=hadoop group=hadoop state=link
  with_items:
    - { src: '/usr/lib64/libsnappy.so', dest: '/apache/hadoop/lib/native/Linux-amd64-64/libsnappy.so' }
  tags: install-hit-apache-hadoop

- name: "** nox ** rename /apache/hbase/lib/native directory if it is not a soft link"
  action: shell test -L /apache/hbase/lib/native || mv /apache/hbase/lib/native /apache/hbase/lib/native.$(date +%F.%T)
  tags: install-hit-apache-hadoop

- name: "** nox ** create link for hadoop and hbase ancillary directories"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/apache/hadoop/lib/native', dest: '/apache/hbase/lib/native', owner: 'hadoop', group: 'hadoop' }
  tags: install-hit-apache-hadoop

