---

# start cluster
#
# **** MUST PROVIDE "-t" OPTIONS WHEN STARTING CLUSTER ****
#
# to start all services (hdfs and mapreduce) on cluster:
#
# 1. replace <LIST> with 'ares-all'
#
# 2. run the following:
#    cd /var/lib/ansible/hadoop-ansible
#
#    to start HDP2 cluster components:
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.all.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-hdp2
#
#    start start HDP1 cluster components: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.all.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-hdp1
#
#
# to start only tasktrackers on cluster:
#
# 1. replace <LIST> with 'ares-all'
#
# 2. run the following:
#    cd /var/lib/ansible/hadoop-ansible
#
#    to start HDP2 Nodemanagers:
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.nm.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-nodemanagers
#
#    to start HDP1 Tasktrackers: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.tt.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-tasktrackers
#
#
# to start only datanodes on cluster:
#
# 1. replace <LIST> with 'ares-all'
#
# 2. run the following:
#    cd /var/lib/ansible/hadoop-ansible
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.dn.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-datanodes
#
#
# to start only hdfs service on cluster (start DN, NN, SNN):
#
# 1. replace <LIST> with 'ares-all'
#
# 2. run the following:
#    cd /var/lib/ansible/hadoop-ansible
#
#    to start HDP2 hdfs service:
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.hdfs.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-hdfs-hdp2
#
#    to start HDP1 hdfs service: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.hdfs.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-hdfs-hdp1
#
# to start only mapreduce service on cluster (start TT, JT, HistoryServer):
#
# 1. replace <LIST> with 'ares-all'
#
# 2. run the following:
#    cd /var/lib/ansible/hadoop-ansible
#
#    to start HDP2 mapreduce service:
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.mr.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-mapred-hdp2
#
#    to start HDP1 mapreduce service: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.start.mr.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/start-ares.yml -t start-mapred-hdp1
#
#
#
#
- hosts: ares-all
  vars_files:
  - /var/lib/ansible/hadoop-ansible/roles/ares/vars/main.yml

  tasks:
  - include: restart/start-hdfs.yml
  - include: restart/start-mapred.yml
