---

# 
# stop cluster
#
# **** MUST PROVIDE "-t" OPTIONS WHEN STOPPING CLUSTER ****
#
# to stop all services (hdfs and mapreduce) on cluster:
#
# 1. replace <LIST> with 'ares-all'
#
# 2. run the following: 
#    cd /var/lib/ansible/hadoop-ansible
#
#    to stop HDP2 cluster components:
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.all.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-hdp2
#
#    stop stop HDP1 cluster components: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.all.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-hdp1
#
#
# to stop only tasktrackers on cluster:
# 
# 1. replace <LIST> with 'ares-all'
# 
# 2. run the following: 
#    cd /var/lib/ansible/hadoop-ansible
#
#    to stop HDP2 Nodemanagers:
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.nm.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-nodemanagers
#
#    to stop HDP1 Tasktrackers: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.tt.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-tasktrackers
#
#
# to stop only datanodes on cluster:
# 
# 1. replace <LIST> with 'ares-all'
# 
# 2. run the following: 
#    cd /var/lib/ansible/hadoop-ansible
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.dn.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-datanodes
#
#
# to stop only hdfs service on cluster (stop DN, NN, SNN):
# 
# 1. replace <LIST> with 'ares-all'
# 
# 2. run the following: 
#    cd /var/lib/ansible/hadoop-ansible
#
#    to stop HDP2 hdfs service:
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.hdfs.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-hdfs-hdp2
#
#    to stop HDP1 hdfs service: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.hdfs.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-hdfs-hdp1
# 
# to stop only mapreduce service on cluster (stop TT, JT, HistoryServer):
# 
# 1. replace <LIST> with 'ares-all'
# 
# 2. run the following: 
#    cd /var/lib/ansible/hadoop-ansible
#
#    to stop HDP2 mapreduce service:
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.mr.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-mapred-hdp2
#
#    to stop HDP1 mapreduce service: (this options is legacy and will go away once cluster has been upgraded to HDP2)
#    time ANSIBLE_LOG_PATH=/var/log/ares.stop.mr.log ansible-playbook -f 48 -i hosts/ares playbooks/cluster-restart/stop-ares.yml -t stop-mapred-hdp1
#
#
#
#
- hosts: ares-all
  vars_files:
  - /var/lib/ansible/hadoop-ansible/roles/ares/vars/main.yml

  tasks:
  - include: restart/stop-mapred.yml
  - include: restart/stop-hdfs.yml
