---

#
# start mapreduce service
#
- name: "** ARES START MAPRED ** Start Tasktrackers"
  action: command /usr/bin/svc -u /service/tasktracker
  when: is_slavenode
  tags: 
    - start-mapred-hdp1
    - start-tasktrackers
    - start-hdp1
  ignore_errors: yes


- name: "** ARES START MAPRED ** Start Nodemanager"
  action: command /usr/bin/svc -u /service/nodemanager
  when: is_slavenode
  tags: 
    - start-mapred-hdp2
    - start-nodemanagers
    - start-hdp2
  ignore_errors: yes


- name: "** ARES START MAPRED ** Start Jobtracker"
  action: command /usr/bin/svc -u /service/jobtracker
  when: is_jobtracker
  tags: 
    - start-mapred-hdp1
    - start-hdp1
  ignore_errors: yes

- name: "** ARES START MAPRED ** Start Resourcemanager"
  action: command /usr/bin/svc -u /service/resourcemanager
  when: is_resourcemanager
  tags: 
    - start-mapred-hdp2
    - start-hdp2
  ignore_errors: yes

- name: "** ARES START MAPRED ** Start History Server"
  action: command /usr/bin/svc -u /service/historyserver
  when: is_historyserver
  tags: 
    - start-mapred-hdp1
    - start-mapred-hdp2
    - start-hdp1
    - start-hdp2
  ignore_errors: yes
