---

#
# stop mapreduce service 
#
- name: "** ARES STOP MAPRED ** Stop History Server"
  action: command /usr/bin/svc -d /service/historyserver
  when: is_historyserver
  tags: 
    - stop-mapred-hdp1
    - stop-mapred-hdp2
    - stop-hdp1
    - stop-hdp2
  ignore_errors: yes 

- name: "** ARES STOP MAPRED ** Stop Tasktrackers"
  action: command /usr/bin/svc -d /service/tasktracker
  when: is_slavenode
  tags: 
    - stop-mapred-hdp1
    - stop-tasktrackers
    - stop-hdp1
  ignore_errors: yes

- name: "** ARES STOP MAPRED ** pkill tasktrackers"
  action: command pkill -9 -u hadoop -f proc_tasktracker
  when: is_slavenode
  tags:
    - stop-mapred-hdp1
    - stop-tasktrackers
    - stop-hdp1
  ignore_errors: yes

- name: "** ARES STOP MAPRED ** Stop Nodemanagers"
  action: command /usr/bin/svc -d /service/nodemanager
  when: is_slavenode
  tags: 
    - stop-mapred-hdp2
    - stop-nodemanagers
    - stop-hdp2
  ignore_errors: yes

- name: "** ARES STOP MAPRED ** pkill Nodemanagers"
  action: command pkill -9 -u hadoop -f proc_nodemanager
  when: is_slavenode
  tags:
    - stop-mapred-hdp2
    - stop-nodemanagers
    - stop-hdp2
  ignore_errors: yes

- name: "** ARES STOP MAPRED ** Stop Jobtracker"
  action: command /usr/bin/svc -d /service/jobtracker
  when: is_jobtracker
  tags: 
    - stop-mapred-hdp1
    - stop-hdp1
  ignore_errors: yes

- name: "** ARES STOP MAPRED ** Stop Resourcemanager"
  action: command /usr/bin/svc -d /service/resourcemanager
  when: is_resourcemanager
  tags: 
    - stop-mapred-hdp2
    - stop-hdp2
  ignore_errors: yes
