#!/bin/sh

# Figures out the rack number based on the 3rd octet of the host's IP address

for ip_addr
do
    case "$ip_addr" in
        [0-9]*.[0-9]*.[0-9]*.[0-9]*)
            echo "/default/rack$(echo $ip_addr | cut -d. -f3)"
        ;;
        *) # See HDMIT-2166 for details
            echo "/default-rack"
            echo "ip_addr: $ip_addr" >> /tmp/topology.$USER.log
        ;;
    esac
done
