---

- hosts: slavenodes
  vars_files:
    - vars/main.yml
  gather_facts: no
  tasks:
     - include: hdp2-deploy-conf.yml

- hosts: masternodes
  vars_files:
    - vars/main.yml
  gather_facts: no
  tasks:
     - include: hdp2-deploy-conf.yml

- hosts: cli-pool
  vars_files:
    - vars/main.yml
  gather_facts: no
  tasks:
     - include: hdp2-deploy-conf.yml
