---

- name: "** ares ** unlink any hadoop related links from previous installation"
  action: file path={{ item }} state=absent
  with_items:
    - /apache/hive
    - /apache/pig
    - /apache/hadoop
  tags: rollback-to-hit-apache-hadoop


- name: "** ares ** create links for hadoop sfw directories"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link
  with_items:
    - { src: '/apache/{{ hdp1_hive }}', dest: '/apache/hive', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_pig }}', dest: '/apache/pig', owner: 'hadoop', group: 'hadoop' }
    - { src: '/apache/{{ hdp1_hadoop }}', dest: '/apache/hadoop', owner: 'hadoop', group: 'hadoop' }
  tags: rollback-to-hit-apache-hadoop

- name: "** ares ** ensure additional apache hadoop directories are present"
  action: file path={{ item }} owner=hadoop group=hadoop mode=0755 state=directory
  with_items:
    - /apache
    - /apache/lib
    - /apache/hadoop/lib
    - /apache/hadoop/pids
  tags: rollback-to-hit-apache-hadoop


- name: "** ares ** create link for jdk 6 "
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/usr/java/jdk1.6.0_45', dest: '/usr/java/latest', owner: 'root', group: 'root' }
  tags: rollback-to-hit-apache-hadoop
