---

# create links for daemontools services

- name: "** ares ** set dt service directories "
  action: file path={{ item }} owner=root group=root mode=0755 state=directory
  with_items:
    - /var/lib/service/nodemanager/log
    - /var/lib/service/nodemanager/env
  tags: setup-dt-links

- name: "** ares ** set dt service ownership/permissions "
  action: file path={{ item.src }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '/var/lib/service/datanode/run', owner: 'root', group: 'root', mode: '0755' }
    - { src: '/var/lib/service/datanode/log/run', owner: 'root', group: 'root', mode: '0755' }
    - { src: '/var/lib/service/nodemanager/run', owner: 'root', group: 'root', mode: '0755' }
    - { src: '/var/lib/service/nodemanager/log/run', owner: 'root', group: 'root', mode: '0755' }
  tags: setup-dt-links

- name: "** ares ** disable nodemanager startup"
  action: file path=/var/lib/service/nodemanager/down owner=root group=root mode=0644 state=touch
  tags: setup-dt-links

- name: "** ares ** create link for nodemanager daemontools service"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/var/lib/service/nodemanager', dest: '/service/nodemanager', owner: 'root', group: 'root' }
  when: "'slavenodes' in group_names"
  tags: setup-dt-links

- name: "** ares ** disable tt startup"
  action: file path=/var/lib/service/tasktracker/down owner=root group=root mode=0644 state=touch
  tags: setup-dt-links

- name: "** ares ** remove tt /service link"
  action: file path=/service/tasktracker state=absent
  tags: setup-dt-links


