---

- name: "** ares ** copy ebay-hdp-hadoop2 repo file"
  action: copy src={{ item }} dest=/etc/yum.repos.d/ebay-hdp-hadoop2-x86_64.repo owner=root group=root mode=0644
  with_items:
    - /var/lib/ansible/hadoop-ansible/roles/common/files/ebay-hdp-hadoop2-x86_64.repo
  tags: install-hdp-lw-hadoop

- name: "** ares ** copy ebay-hdp-2.1.3-x86_64.repo repo file"
  action: copy src={{ item }} dest=/etc/yum.repos.d/ebay-hdp-2.1.3-x86_64.repo owner=root group=root mode=0644
  with_items:
    - /var/lib/ansible/hadoop-ansible/roles/common/files/ebay-hdp-2.1.3-x86_64.repo
  tags: install-hdp-lw-hadoop


- name: "** ares ** yum clean all on repo"
  action: command yum clean all
  tags: install-hdp-lw-hadoop

- name: "** ares ** install hadoop RHEL 6"
  shell: /bin/rpm -ivh /var/tmp/centos6/ebay-hdp-lw-hadoop-2.4.1-EBAY-11-1.0-1.el6.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** install pig RHEL 6"
  shell: /bin/rpm -ivh /var/tmp/centos6/ebay-hdp-ga-pig-0.12.1.2.1.3.6-2-1.0-1.el6.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** install hive RHEL 6"
  shell: /bin/rpm -ivh /var/tmp/centos6/ebay-hdp-ga-hive-0.13.0.2.1.3.6-2-bin-1.0-1.el6.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** install bigtop RHEL 6"
  shell: /bin/rpm -ivh /var/tmp/centos6/bigtop-jsvc-1.0.10-1.el6.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  ignore_errors: yes
  tags: hadoop-install


- name: "** ares ** install hadoop RHEL 5"
  shell: /bin/rpm -ivh /var/tmp/centos5/ebay-hdp-lw-hadoop-2.4.1-EBAY-11-1.0-1.el5.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 5
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** install pig RHEL 5"
  shell: /bin/rpm -ivh /var/tmp/centos5/ebay-hdp-lw-pig-0.12.1.2.1.3.6-2-1.0-1.el5.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 5
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** install hive RHEL 5"
  shell: /bin/rpm -ivh /var/tmp/centos5/ebay-hdp-lw-hive-0.13.0.2.1.3.6-2-bin-1.0-1.el5.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 5
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** install bigtop RHEL 5"
  shell: /bin/rpm -ivh /var/tmp/centos5/bigtop-jsvc-1.0.10-1.x86_64.rpm
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 5
  ignore_errors: yes
  tags: hadoop-install

- name: "** ares ** copy all the contenets of native. i.e libsnappy and Linux-amd64-64 "
  action: copy src=/var/tmp/jars/libsnappy.so.1.1.4 dest=/apache/{{ hdp2_hadoop }}/lib/native/ owner=hadoop group=hadoop mode=644
  tags: install-hdp-lw-hadoop
  ignore_errors: yes

- name: "** ares ** create link for libsnappy "
  action: file src={{ item.src }} dest={{ item.dest }} owner=hadoop group=hadoop state=link force=yes
  with_items:
    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/libsnappy.so.1.1.4', dest: '/apache/{{ hdp2_hadoop }}/lib/native/libsnappy.so' }
    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/libsnappy.so.1.1.4', dest: '/apache/{{ hdp2_hadoop }}/lib/native/libsnappy.so.1' }
  tags: install-hdp-lw-hadoop
  tags: create-snappy-links
  ignore_errors: yes

- name: "** ares ** deploy hdmi hdp hadoop jars"
  action: copy src={{ item.src }} dest={{ item.dest }} owner=hadoop group=hadoop mode=0644
  with_items:
    - { src: '/var/tmp/jars/hadoop-ebay-2.4.1-EBAY-11.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/hadoop-ebay-2.4.1-EBAY-11.jar' }
    - { src: '/var/tmp/jars/opentoken-adapter-2.4.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/opentoken-adapter-2.4.jar' }
    - { src: '/var/tmp/jars/opentoken-agent-2.4.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/opentoken-agent-2.4.jar' }
  tags: install-hdp-lw-hadoop

- name: "** ares ** install mysql java connector jar"
  action: copy src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '/var/tmp/jars/mysql-connector-java-5.0.8-bin.jar', dest: '/usr/local/lib/mysql-connector-java-5.0.8-bin.jar', owner: 'hadoop', group: 'hadoop', mode: '0644' }
  tags:
    - install-hdp-lw-hadoop
    - install-mysql-connector

- name: "** ares ** install lzo jar"
  action: copy src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '/var/tmp/jars/hadoop-lzo-0.6.0.jar', dest: '/apache/{{ hdp2_hadoop }}/lib/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
  tags:
    - install-hdp-lw-hadoop


- name: "** ares ** create link for hadoop-lzo-0.6.0.jar"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/apache/{{ hdp2_hadoop }}/lib/hadoop-lzo-0.6.0.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/hadoop-lzo-0.6.0.jar', owner: 'hadoop', group: 'hadoop' }
  tags:
    - enable-hdp-lw-hadoop


- name: "** ares ** install libgpl centos5"
  action: copy src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '/var/tmp/centos5/Linux-amd64-64/libgplcompression.a', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
    - { src: '/var/tmp/centos5/Linux-amd64-64/libgplcompression.la', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
    - { src: '/var/tmp/centos5/Linux-amd64-64/libgplcompression.so.0.0.0', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 5
  ignore_errors: yes
  tags:
    - install-hdp-lw-hadoop
    - install-gpl-hadoop


- name: "** ares ** install libgpl centos6"
  action: copy src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '/var/tmp/centos6/Linux-amd64-64/libgplcompression.a', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
    - { src: '/var/tmp/centos6/Linux-amd64-64/libgplcompression.la', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
    - { src: '/var/tmp/centos6/Linux-amd64-64/libgplcompression.so.0.0.0', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/', owner: 'hadoop', group: 'hadoop', mode: '0644' }
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
  ignore_errors: yes
  tags:
    - install-hdp-lw-hadoop
    - install-gpl-hadoop

- name: "** ares ** create link for libgplcompression "
  action: file src={{ item.src }} dest={{ item.dest }} owner=hadoop group=hadoop state=link force=yes
  with_items:
    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.so.0.0.0', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.so.0' }
    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.so.0.0.0', dest: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.so' }
  tags:
    - install-hdp-lw-hadoop
    - install-gpl-hadoop
  ignore_errors: yes


# ebay-hdp-lw-hadoop build-61 RPM will install with owner:group set to user 'hadoop'
- name: "** ares ** chown hdp2 installation, except hadoop dir"
  action: command chown -R hadoop:hadoop /apache/{{ item }}
  with_items:
    - '{{ hdp2_hive }}'
    - '{{ hdp2_pig }}'
  tags: install-hdp-lw-hadoop

- name: "** ares ** stat hdp2 install directories"
  action: stat path={{ item }}
  with_items:
    - '/apache'
    - '/apache/{{ hdp2_hadoop }}'
    - '/apache/{{ hdp2_hadoop }}/etc'
    - '/apache/{{ hdp2_hadoop }}/etc/hadoop'
  register: hdp2installdirs
  tags: install-hdp-lw-hadoop

- name: "** ares ** chown hdp2 hadoop dir"
  action: file path={{ item.item }} owner=root group=hadoop mode=0755
  with_items: hdp2installdirs.results
  when: item.stat.isdir is defined and item.stat.isdir == true
  tags: install-hdp-lw-hadoop

- name: "** ares ** install jdk 7 "
  #action: yum name=http://installsvc.vip.phx.ebay.com/packages/hs/ebayextras/x86_64/6/RPMS/jdk/jdk-7u60/jdk-1.7.0_60-fcs-1.el6.x86_64.rpm state=present
  shell: /bin/rpm -ivh /var/tmp/centos6/jdk-1.7.0_60-fcs-1.el6.x86_64.rpm
  tags: jdk7-install
  ignore_errors: yes

#- name: "** ares ** chown hdp2 lzo installation"
#  action: file path={{ item.src }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
#  with_items:
#    - { src: '/apache/{{ hdp2_hadoop }}/lib/hadoop-lzo-0.6.0.jar', owner: 'hadoop', group: 'hadoop', mode: '644' }
#    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.so.0.0.0', owner: 'hadoop', group: 'hadoop', mode: '664' }
#    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.la', owner: 'hadoop', group: 'hadoop', mode: '664' }
#    - { src: '/apache/{{ hdp2_hadoop }}/lib/native/Linux-amd64-64/libgplcompression.a', owner: 'hadoop', group: 'hadoop', mode: '664' }
#  tags:
#    - enable-hdp-lw-hadoop
#    - enable-hadoop-permissions

#- name: "** ares ** create link for hadoop-lzo-0.6.0.jar"
#  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
#  with_items:
#    - { src: '/apache/{{ hdp2_hadoop }}/lib/hadoop-lzo-0.6.0.jar', dest: '/apache/{{ hdp2_hadoop }}/share/hadoop/common/lib/hadoop-lzo-0.6.0.jar', owner: 'hadoop', group: 'hadoop' }
#  tags:
#    - enable-hdp-lw-hadoop
#    - enable-hadoop-permissions


- name: "** ares ** check if old conf dir is present"
  action: stat path=/apache/{{ item }}
  with_items:
    - "{{ hdp2_hadoop }}/conf"
    - "{{ hdp2_hive }}/conf"
    - "{{ hdp2_pig }}/conf"
    - "{{ hdp2_hadoop }}/etc/hadoop"
  register: confdir
  tags:
    - hadoop-conf-dir-check
    - enable-hdp-lw-hadoop
    - enable-hadoop-permissions

- name: "** ares ** rename old conf dir if present"
  action: shell mv /apache/{{ item.item }} /apache/{{ item.item }}.$(date +%F.%T)
  with_items: confdir.results
  when: item.stat.isdir is defined and item.stat.isdir == true
  tags:
    - hadoop-conf-dir-check
    - enable-hdp-lw-hadoop
    - enable-hadoop-permissions

- name: "** ares ** create link for hdp2 conf directories"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '{{ hdp2_conf_dir }}/hadoop/conf', dest: '/apache/{{ hdp2_hadoop }}/conf', owner: 'root', group: 'hadoop' }
    - { src: '{{ hdp2_conf_dir }}/hive/conf', dest: '/apache/{{ hdp2_hive }}/conf', owner: 'hadoop', group: 'hadoop' }
    - { src: '{{ hdp2_conf_dir }}/pig/conf', dest: '/apache/{{ hdp2_pig }}/conf', owner: 'hadoop', group: 'hadoop' }
  tags:
    - enable-hdp-lw-hadoop
    - enable-hadoop-permissions


# link to hdp2 hadoop conf
- name: "** ares ** create link for hdp2 hadoop config"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '{{ hdp2_conf_dir }}/hadoop/conf', dest: '/apache/{{ hdp2_hadoop }}/etc/hadoop', owner: 'root', group: 'hadoop' }
  tags:
    - enable-hdp-lw-hadoop
    - enable-hadoop-permissions

- name: "** ares ** chown hdp2 configs"
  action: command chown -R hadoop:hadoop {{ hdp2_conf_dir }}
  tags:
    - set-hdp2-config
    - deploy-hdp2-configs
    - enable-hadoop-permissions


- name: "** ares ** chown hdp2 container-executor file"
  action: file path={{ item.src }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: '/apache/{{ hdp2_hadoop }}/bin/container-executor', owner: 'root', group: 'hadoop', mode: '6050' }
    - { src: '/apache/{{ hdp2_hadoop }}/conf/container-executor.cfg', owner: 'root', group: 'hadoop', mode: '0400' }
    - { src: '/apache/{{ hdp2_hadoop }}', owner: 'root', group: 'hadoop', mode: '0775' }
    - { src: '/apache/{{ hdp2_hadoop }}/etc', owner: 'root', group: 'hadoop', mode: '0775' }
  tags:
    - enable-hdp-lw-hadoop
    - deploy-hdp2-configs
    - enable-hadoop-permissions


- name: "** ares ** chown Linux-amd directory"
  action: command chown  hadoop:hadoop /apache/hadoop-2.4.1-EBAY-11/lib/native/Linux-amd64-64
  tags:
    - set-hdp2-config
    - deploy-hdp2-configs
    - enable-hadoop-permissions
    - enable-Linuixamd-permission

- name: "** ares ** chown lzo jar"
  action: command chown  hadoop:hadoop /apache/hadoop-2.4.1-EBAY-11/lib/hadoop-lzo-0.6.0.jar
  tags:
    - set-hdp2-config
    - deploy-hdp2-configs
    - enable-hadoop-permissions
    - enable-Linuixamd-permission

- name: "** ares ** enable mysql connector jar"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/usr/local/lib/mysql-connector-java-5.0.8-bin.jar', dest: '/apache/{{ hdp2_hive }}/lib/mysql-connector-java-5.0.8-bin.jar', owner: 'hadoop', group: 'hadoop' }
  tags:
    - enable-hdp213-hadoop
    - enable-mysql-connector
    - enable-hadoop-permissions


