# daemontools configs

- name: "** ares ** disable nodemanager startup"
  action: file path=/var/lib/service/nodemanager/down owner=root group=root mode=0644 state=touch
  when: "'slavenodes' in group_names"
  tags: 
  - get-hadoop2-config
  - run-before-upgrade

- name: "** ares ** create link for nodemanager daemontools service"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/var/lib/service/nodemanager', dest: '/service/nodemanager', owner: 'root', group: 'root' }
  when: "'slavenodes' in group_names"
  tags: 
  - get-hadoop2-config
  - run-before-upgrade

- name: "** ares ** disable resourcemanager startup"
  action: file path=/var/lib/service/resourcemanager/down owner=root group=root mode=0644 state=touch
  when: "'resourcemanager' in group_names"
  tags:
  - get-hadoop2-config
  - run-before-upgrade

- name: "** ares ** create link for resourcemanager daemontools service"
  action: file src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} state=link force=yes
  with_items:
    - { src: '/var/lib/service/resourcemanager', dest: '/service/resourcemanager', owner: 'root', group: 'root' }
  when: "'resourcemanager' in group_names"
  tags:
  - get-hadoop2-config
  - run-before-upgrade
